[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "22"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.3"
NODE_VERSION = "22"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.3"
NODE_VERSION = "22"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"